Collapse PRs #114 and #120
AmericanRedCross/damage-assessment-bot pull request #131
Opened 2018-10-24 00:54 UTC by maxnorth

Collapses PR's #114  and #120 plus changes to address comments on those PR's.

2018-10-25 10:07 UTC, blueelvis requested changes

2018-10-29 16:31 UTC, maxnorth commented on api/src/chat/prompts/RcdaPromptAdaptiveCard.ts
> +            if (!turnZero) {
I'm inclined to say let's not worry too much about this for this PR, I just wanted to include the stub of what I had, but once we have a PR that actually needs to use this functionality we can make sure it's working as expected.

2018-10-30 06:46 UTC, blueelvis commented on api/src/chat/prompts/RcdaPromptAdaptiveCard.ts
> +            if (!turnZero) {
Agreed. Merging this PR.

2018-10-30 06:47 UTC, blueelvis approved these changes

2018-10-30 06:47 UTC, merged