Add myanmar disaster assessment form enums
AmericanRedCross/damage-assessment-bot pull request #147
Opened 2018-11-17 19:18 UTC by maxnorth

2018-11-19 13:55 UTC, blueelvis requested changes

2018-11-19 14:01 UTC, maxnorth commented on common/src/models/resources/disaster-assessment/enums/MyanmarAffectedGroups.ts
> +    DisplacedIdp = "DisplacedIdp",
The approach I'm taking is to treat these enums strictly as value identifiers, and not focus on how the value renders in any particular application. In the localization PR, check out api/src/chat/localization/RcdaMyanmarText for how I associate these values to displayed text.

2018-11-19 14:17 UTC, maxnorth commented on common/src/models/resources/disaster-assessment/enums/MyanmarAffectedGroups.ts
> +    DisplacedIdp = "DisplacedIdp",
The objective is for these to be permanent database values that we can query against, aggregate on, etc. If we mix the concepts of value ids and display text, people will be inclined to update these and make them inconsistent across records.

2018-11-19 21:55 UTC, merged

2018-11-20 20:51 UTC, blueelvis commented on common/src/models/resources/disaster-assessment/enums/MyanmarAffectedGroups.ts
> +    DisplacedIdp = "DisplacedIdp",
@maxnorth - Got it! Thanks for the clarification.